export function modeTypes(type) {
  if(type === 0){ return 'None'; }
  else if(type === 2){ return 'Story'; }
  else if(type === 3){ return 'Strike'; }
  else if(type === 4){ return 'Raid'; }
  else if(type === 5){ return 'AllPvP'; }
  else if(type === 6){ return 'Patrol'; }
  else if(type === 7){ return 'AllPvE'; }
  else if(type === 10){ return 'Control'; }
  else if(type === 12){ return 'Clash'; }
  else if(type === 15){ return 'CrimsonDoubles'; }
  else if(type === 16){ return 'Nightfall'; }
  else if(type === 17){ return 'HeroicNightfall'; }
  else if(type === 18){ return 'AllStrikes'; }
  else if(type === 19){ return 'IronBanner'; }
  else if(type === 25){ return 'AllMayhem'; }
  else if(type === 31){ return 'Supremacy'; }
  else if(type === 32){ return 'PrivateMatchesAll'; }
  else if(type === 37){ return 'Survival'; }
  else if(type === 38){ return 'Countdown'; }
  else if(type === 39){ return 'TrialsOfTheNine'; }
  else if(type === 40){ return 'Social'; }
  else if(type === 41){ return 'TrialsCountdown'; }
  else if(type === 42){ return 'TrialsSurvival'; }
  else if(type === 43){ return 'IronBannerControl'; }
  else if(type === 44){ return 'IronBannerClash'; }
  else if(type === 45){ return 'IronBannerSupremacy'; }
  else if(type === 46){ return 'ScoredNightfall'; }
  else if(type === 47){ return 'ScoredHeroicNightfall'; }
  else if(type === 48){ return 'Rumble'; }
  else if(type === 49){ return 'AllDoubles'; }
  else if(type === 50){ return 'Doubles'; }
  else if(type === 51){ return 'PrivateMatchesClash'; }
  else if(type === 52){ return 'PrivateMatchesControl'; }
  else if(type === 53){ return 'PrivateMatchesSupremacy'; }
  else if(type === 54){ return 'PrivateMatchesCountdown'; }
  else if(type === 55){ return 'PrivateMatchesSurvival'; }
  else if(type === 56){ return 'PrivateMatchesMayhem'; }
  else if(type === 57){ return 'PrivateMatchesRumble'; }
  else if(type === 58){ return 'HeroicAdventure'; }
  else if(type === 59){ return 'Showdown'; }
  else if(type === 60){ return 'Lockdown'; }
  else if(type === 61){ return 'Scorched'; }
  else if(type === 62){ return 'ScorchedTeam'; }
  else if(type === 63){ return 'Gambit'; }
  else if(type === 64){ return 'AllPvECompetitive'; }
  else if(type === 65){ return 'Breakthrough'; }
  else if(type === 66){ return 'BlackArmoryRun'; }
  else if(type === 67){ return 'Salvage'; }
  else if(type === 68){ return 'IronBannerSalvage'; }
  else if(type === 69){ return 'PvPCompetitive'; }
  else if(type === 70){ return 'PvPQuickplay'; }
  else if(type === 71){ return 'ClashQuickplay'; }
  else if(type === 72){ return 'ClashCompetitive'; }
  else if(type === 73){ return 'ControlQuickplay'; }
  else if(type === 74){ return 'ControlCompetitive'; }
  else if(type === 75){ return 'GambitPrime'; }
  else if(type === 76){ return 'Reckoning'; }
  else if(type === 77){ return 'Menagerie'; }
  else { return 'New Mode'; }
}
